entryPoints:
  web:
    address: ":80"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: web
    watch: true

log:
  level: INFO
  format: common

accessLog:
  format: common
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-599"
